# Generated by Django 3.2.3 on 2021-06-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_auto_20210601_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentdonation',
            old_name='instrument',
            new_name='name',
        ),
    ]
