# Generated by Django 3.2.3 on 2021-06-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0004_alter_instrumentdonation_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
